### ISSUE TITLE
Q: Can you add custom configuration to ignore TODOs when they come with a Jira ID?

### ISSUE THREAD

**Issue by Evgenios95** [azu/textlint-rule-no-todo#7]
In my project, I use a Format which is of the following format:`// TODO [TIE-1329]:`

For consistency reasons, I would like to be able to install `textlint-rule-no-todo`, but configure it in such a way, that if the `TODO` is followed by `[]` and an `ID` inside it, it shouldn't throw errors.

Is that possible in any way at the moment?

**Comment by azu** [comment]
No.
I've created this rule for documentation of textlint.
https://textlint.github.io/docs/rule.html
So, It has only minimal feature.

You can creating another rule or use next rule.
https://github.com/textlint-rule/textlint-rule-pattern
